### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DantasB** [samueldurantes/susi#6]
I've opened the project and searched for the data for Computer Science at UFRJ and i got two records. These two are related to the first and the second SISU period?

If yes, i think that could have this information in the card. Also you could increment the project with the data of the previous sisu's, so the user could map the increase or decrease of the cutoff scores.

![image](https://user-images.githubusercontent.com/15825133/219517158-7054b61d-8ed8-4ec8-8088-72ca97b4ca46.png)

**Comment by samueldurantes** [comment]
> These two are related to the first and the second SISU period?

Yes, both periods. Well noted, I will add this field!!

> so the user could map the increase or decrease of the cutoff scores

Sounds good to me. Could you open another with more details?

**Comment by DantasB** [comment]
OFC! I'll do that.
